# Generated by Django 4.0 on 2022-04-16 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leasadmin', '0001_initial'),
        ('dealerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacakage',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='de_by', to='leasadmin.user_accounts'),
        ),
        migrations.AddField(
            model_name='pacakage',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_by', to='leasadmin.user_accounts'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='del_by', to='leasadmin.user_accounts'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealerapp.pacakage'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_by', to='leasadmin.user_accounts'),
        ),
    ]
