# Generated by Django 4.0 on 2022-04-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='approved',
            new_name='status',
        ),
    ]
