# Generated by Django 4.0 on 2022-04-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0003_rename_approved_dealer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
