# Generated by Django 4.0 on 2022-04-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasadmin', '0002_dealer_types'),
        ('dealerapp', '0004_dealer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='dealer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_type', to='leasadmin.dealer_types'),
        ),
    ]
