# Generated by Django 4.0 on 2022-04-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0005_alter_dealer_dealer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacakage',
            name='created_by',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='deleted_by',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='updated_by',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pacakage',
            name='deleted_by',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pacakage',
            name='updated_by',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
