# Generated by Django 4.0 on 2022-05-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0007_alter_dealer_package_delete_pacakage'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('details', models.CharField(max_length=40, null=True)),
                ('is_deleted', models.IntegerField(null=True)),
                ('deleted_by', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
