# Generated by Django 4.0 on 2022-06-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0008_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='booked_leads',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
