# Generated by Django 4.0 on 2022-06-05 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0010_b_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_leads',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealerapp.dealer'),
        ),
    ]
