# Generated by Django 4.0 on 2022-06-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0011_b_leads_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_leads',
            name='deal_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
