# Generated by Django 4.0 on 2022-06-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0012_b_leads_deal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b_leads',
            old_name='orderId',
            new_name='phone',
        ),
    ]
