# Generated by Django 4.0 on 2022-06-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0013_rename_orderid_b_leads_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_leads',
            name='deal_id',
            field=models.IntegerField(max_length=40, null=True),
        ),
    ]
