# Generated by Django 4.0.5 on 2022-06-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0014_alter_b_leads_deal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='booked_leads',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='package',
            field=models.IntegerField(null=True),
        ),
    ]
