# Generated by Django 4.0 on 2022-04-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasadmin', '0002_dealer_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer_types',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user_accounts',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='dealer_types',
            name='created_by',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user_accounts',
            name='created_by',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dealer_types',
            name='deleted_by',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dealer_types',
            name='updated_by',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user_accounts',
            name='deleted_by',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user_accounts',
            name='updated_by',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
